### PR TITLE
Add hosting of built wheel at PyPI - develop

### PR DESCRIPTION
**Pull request by kccwing**
Identical to #297 - but merging into develop.

### CODE REVIEW

**Review by wong-hl — COMMENTED** [review]
If it's identical to #297, can't you just merge the main branch into develop?

**Comment by kccwing** [comment]
> If it's identical to #297, can't you just merge the main branch into develop?

usually I tend to merge main into develop right before a PR (from develop to main) - does it make more sense to do hot fixes merging one then the other, or does it not matter?

**Comment by wong-hl** [comment]
> > If it's identical to #297, can't you just merge the main branch into develop?
> 
> usually I tend to merge main into develop right before a PR (from develop to main) - does it make more sense to do hot fixes merging one then the other, or does it not matter?

In terms of the end result, it doesn’t matter. The order only matters for the git history (mainly the merge commit). Ideally, the hot fix should’ve been merged into `dev` first, then merge `dev` into `main`. But, this is workflow stuff so it makes sense to merge it directly into `main`. 

This is really a style/preference sort of thing. By merging `main` into `dev`, you have one less PR and a cleaner git history as the same commits aren’t merged twice.

**Review by ben-l-p — APPROVED** [review]
Happy for this to be merged if the previous commits are squashed - good addition Kelvin!

**Comment by kccwing** [comment]
Thanks both for the suggestions and reviews, @ben-l-p & @wong-hl!!

**Pull request merged**
